export const RegisteredStudentsData = [
  {
    id: "CHEM1",
    studentid: "123",
    studentname: "Asher Sky",
    studentemail: "asher.sky@gmail.com",
    status: false,
  },
  {
    id: "CHEM1",
    studentid: "124",
    studentname: "Bodhi Zen",
    studentemail: "bodhi.zen@gmail.com",
    status: false,
  },
  {
    id: "CHEM1",
    studentid: "125",
    studentname: "Caspian Blue",
    studentemail: "capsian.blue@gmail.com",
    status: false,
  },
  {
    id: "PHY1",
    studentid: "126",
    studentname: "Brielle Starlight",
    studentemail: "brielle.starlight@gmail.com",
    status: false,
  },
  {
    id: "PHY1",
    studentid: "127",
    studentname: "Elowen Moon",
    studentemail: "elowen.moon@gmail.com",
    status: false,
  },
  {
    id: "PHY1",
    studentid: "345",
    studentname: "Jeniffer Smith",
    studentemail: "jeniffern@gmail.com",
    status: false,
  },
  {
    id: "PHY1",
    studentid: "986",
    studentname: "Ann Williams",
    studentemail: "ann@gmail.com",
    status: false,
  },
  {
    id: "PHY1",
    studentid: "438",
    studentname: "Peter Brown",
    studentemail: "peter@gmail.com",
    status: false,
  },
  {
    id: "BIO1",
    studentid: "126",
    studentname: "Brielle Starlight",
    studentemail: "brielle.starlight@gmail.com",
    status: false,
  },
  {
    id: "BIO1",
    studentid: "124",
    studentname: "Bodhi Zen",
    studentemail: "bodhi.zen@gmail.com",
    status: false,
  },
  {
    id: "MATH1",
    studentid: "123",
    studentname: "Asher Sky",
    studentemail: "asher.sky@gmail.com",
    status: false,
  },
  {
    id: "MATH1",
    studentid: "125",
    studentname: "Caspian Blue",
    studentemail: "capsian.blue@gmail.com",
    status: false,
  },
];