export const StudentQuestionsData = [
  {
    id: "CHEM1",
    sessionDate: "15-10-2023",
    subject: "Chemistry",
    lesson: "Chemical Reactions",
    questionid:"CHEM1-1",
    question: "What is the balanced equation for photosynthesis?",
    status: false,
  },
  {
    id: "CHEM1",
    sessionDate: "15-10-2023",
    subject: "Chemistry",
    lesson: "Chemical Bonding",
    questionid:"CHEM1-2",
    question: "WWhat is the difference between a covalent bond and an ionic bond??",
    status: false,
  },
  {
    id: "CHEM1",
    sessionDate: "15-10-2023",
    subject: "Chemistry",
    lesson: "Chemical Reactions",
    questionid:"CHEM1-3",
    question: "What is the difference between an exothermic reaction and an endothermic reaction?",
    status: false,
    }, 
    {
    id: "CHEM1",
    sessionDate: "15-10-2023",
    subject: "Chemistry",
    lesson: "Gases",
    questionid:"CHEM1-4",
    question: "What is the relationship between temperature and pressure in a gas?",
    status: false,
  },

  {
    id: "PHY1",
    sessionDate: "18-10-2023",
    subject: "Physics",
    lesson: "Newton's Laws of Motion",
    questionid:"PHY1-1",
    question: "Explain Newton's first law of motion.",
    status: false,
  },
  {
    id: "BIO1",
    sessionDate: "20-10-2023",
    subject: "Biology",
    lesson: "Cell Biology",
    questionid:"BIO1-1",
    question: "Describe the structure of a plant cell.",
    status: false,
  },
  {
    id: "MATH1",
    sessionDate: "22-10-2023",
    subject: "Mathematics",
    lesson: "Algebra",
    questionid:"MATH1-1",
    question: "Solve the quadratic equation x^2 - 4x + 4 = 0.",
    status: false,
  },
];